title: NBA 实时速览精读
description: 美媒 NBA 动态全自动追更，精简编译与核心要点拆解。
future: true
timezone: Asia/Shanghai
theme: minima

# 必须设置 baseurl 指向你的项目仓库名（注意前面有斜杠）
# baseurl: "/NBA-Quick-News-2.0"
# url: "https://cibstan1999.github.io"

# 排除 README，不让它变成网页
exclude:
  - README.md
